language: go

go:
  - 1.3

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeSuites --failOnPending --trace --race
